---
apiVersion: v1
kind: Template
metadata:
  name: example-template
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: demo-app
      labels:
        app: demo-app
        service: demo-app
    spec:
      ports:
      - name: demo-app
        port: 8080
        protocol: TCP
      selector:
        service: demo-app

  - apiVersion: v1
    kind: Route
    metadata:
      name: demo-app
      labels:
        app: demo-app
        service: demo-app
    spec:
      to:
        kind: Service
        name: demo-app

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: demo-app
      labels:
        app: demo-app
        service: demo-app
    spec:
      replicas: 1
      selector:
        app: demo-app
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: demo-app
            service: demo-app
        spec:
          containers:
            - name: demo-app
              image: docker-registry.default.svc:5000/araszka-playground/demo-app:latest
              imagePullPolicy: Always
              resources:
                limits:
                  memory: 1Gi
              ports:
              - containerPort: 8080
                protocol: TCP
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 5
                timeoutSeconds: 1
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 3
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            from:
              kind: "ImageStreamTag"
              name: "demo-app:latest"
            containerNames:
              - demo-app

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: demo-app
      name: demo-app
    spec:
      output:
        to:
          kind: DockerImage
          name: docker-registry.default.svc:5000/araszka-playground/demo-app:latest
      runPolicy: Serial
      resources:
        limits:
          memory: "2Gi"
      source:
        git:
          uri: https://github.com/kusha/rhv3-logging-demo.git
          ref: master
        contextDir: example_app
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: DockerImage
            name: rhscl/python-36-rhel7:latest
        type: Docker

